on: push
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.1.0
      with:
        args: pub get

    - name: enable web
      uses: steebchen/flutter@v1.1.0
      with:
        args: config --enable-web

    - name: build web
      uses: steebchen/flutter@v1.1.0
      with:
        args: build web --release
