on: 
  push:
    branches:
      - main
name: FlutterBuild
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Goto Dir
      run:
        cd ./flo_main

    - name: install dependencies
      run:
        cd ./flo_main;flutter pub get

    - name: enable web
      run:
        cd ./flo_main;flutter config --enable-web
    - name: build web
      run:
        cd ./flo_main;flutter build web --release
