on: 
  push:
    branches:
      - master
name: FlutterBuild
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
       flutter-version: '2.0.0'

    - name: install dependencies
      run:
        cd ./flo_main;flutter pub get

    - name: enable web
      run:
        cd ./flo_main;flutter config --enable-web
    - name: build web
      run:
        cd ./flo_main;flutter build web --release
